services:
  - type: web
    name: sidecar
    runtime: image
    plan: free
    image:
      url: ghcr.io/joojoooo/toastflix-sidecar:latest
    envVars:
      - key: SIDECAR_ADMIN_TOKEN
        generateValue: true
      - key: SIDECAR_CACHE_DIR
        value: /app/data
